// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/_app.tsx';
import * as $1 from './routes/index.tsx';
import * as $2 from './routes/release.tsx';
import * as $$0 from './islands/RegionList.tsx';

const manifest = {
	routes: {
		'./routes/_app.tsx': $0,
		'./routes/index.tsx': $1,
		'./routes/release.tsx': $2,
	},
	islands: {
		'./islands/RegionList.tsx': $$0,
	},
	baseUrl: import.meta.url,
};

export default manifest;
