import type { CountryCode } from '@/harmonizer/types.ts';
import { isDefined } from '@/utils/predicate.ts';

/**
 * Converts a Discogs "country" name into an array of country codes.
 */
export function convertCountryStringToCodes(countryName: string): CountryCode[] | undefined {
	// TODO: handle groups of multiple countries and historical regions
	const countryCode = countryNameToCode[countryName];
	if (countryCode) {
		return [countryCode];
	}

	const countryCodes = countryName.split(countrySeparator).map((part) => countryNameToCode[part]);
	if (countryCodes.every(isDefined)) {
		return countryCodes;
	}
}

/**
 * Maps a country name (as used on Discogs) to a country code.
 *
 * Country names extracted from "subform/view:countries" data on release edit page.
 */
const countryNameToCode: Record<string, CountryCode | undefined> = {
	Afghanistan: 'AF',
	Albania: 'AL',
	Algeria: 'DZ',
	'American Samoa': 'AS',
	Andorra: 'AD',
	Angola: 'AO',
	Anguilla: 'AI',
	Antarctica: 'AQ',
	'Antigua & Barbuda': 'AG',
	Argentina: 'AR',
	Armenia: 'AM',
	Aruba: 'AW',
	Australia: 'AU',
	Austria: 'AT',
	Azerbaijan: 'AZ',
	'Bahamas, The': 'BS',
	Bahrain: 'BH',
	Bangladesh: 'BD',
	Barbados: 'BB',
	Belarus: 'BY',
	Belgium: 'BE',
	Belize: 'BZ',
	Benin: 'BJ',
	Bermuda: 'BM',
	Bhutan: 'BT',
	Bolivia: 'BO',
	'Bosnia & Herzegovina': 'BA',
	Botswana: 'BW',
	Brazil: 'BR',
	'British Indian Ocean Territory': 'IO',
	'British Virgin Islands': 'VG',
	Brunei: 'BN',
	Bulgaria: 'BG',
	'Burkina Faso': 'BF',
	Burma: 'MM', // Myanmar
	Burundi: 'BI',
	Cambodia: 'KH',
	Cameroon: 'CM',
	Canada: 'CA',
	'Cape Verde': 'CV',
	'Cayman Islands': 'KY',
	'Central African Republic': 'CF',
	Chad: 'TD',
	Chile: 'CL',
	China: 'CN',
	'Christmas Island': 'CX',
	'Cocos (Keeling) Islands': 'CC',
	Colombia: 'CO',
	Comoros: 'KM',
	'Congo, Democratic Republic of the': 'CD',
	'Congo, Republic of the': 'CG',
	'Cook Islands': 'CK',
	'Costa Rica': 'CR',
	Croatia: 'HR',
	Cuba: 'CU',
	'Curaçao': 'CW',
	Cyprus: 'CY',
	'Czech Republic': 'CZ',
	Denmark: 'DK',
	Djibouti: 'DJ',
	Dominica: 'DM',
	'Dominican Republic': 'DO',
	'East Timor': 'TL',
	Ecuador: 'EC',
	Egypt: 'EG',
	'El Salvador': 'SV',
	'Equatorial Guinea': 'GQ',
	Eritrea: 'ER',
	Estonia: 'EE',
	Ethiopia: 'ET',
	'Falkland Islands': 'FK',
	'Faroe Islands': 'FO',
	Fiji: 'FJ',
	Finland: 'FI',
	France: 'FR',
	'French Guiana': 'GF',
	'French Polynesia': 'PF',
	'French Southern & Antarctic Lands': 'TF',
	Gabon: 'GA',
	'Gambia, The': 'GM',
	Georgia: 'GE',
	Germany: 'DE',
	Ghana: 'GH',
	Gibraltar: 'GI',
	Greece: 'GR',
	Greenland: 'GL',
	Grenada: 'GD',
	Guadeloupe: 'GP',
	Guam: 'GU',
	Guatemala: 'GT',
	Guernsey: 'GG',
	Guinea: 'GN',
	'Guinea-Bissau': 'GW',
	Guyana: 'GY',
	Haiti: 'HT',
	Honduras: 'HN',
	'Hong Kong': 'HK',
	Hungary: 'HU',
	Iceland: 'IS',
	India: 'IN',
	Indonesia: 'ID',
	Iran: 'IR',
	Iraq: 'IQ',
	Ireland: 'IE',
	'Isle Of Man': 'IM',
	Israel: 'IL',
	Italy: 'IT',
	'Ivory Coast': 'CI',
	Jamaica: 'JM',
	Japan: 'JP',
	Jersey: 'JE',
	Jordan: 'JO',
	Kazakhstan: 'KZ',
	Kenya: 'KE',
	Kiribati: 'KI',
	Kosovo: 'XK',
	Kuwait: 'KW',
	Kyrgyzstan: 'KG',
	Laos: 'LA',
	Latvia: 'LV',
	Lebanon: 'LB',
	Lesotho: 'LS',
	Liberia: 'LR',
	Libya: 'LY',
	Liechtenstein: 'LI',
	Lithuania: 'LT',
	Luxembourg: 'LU',
	Macau: 'MO',
	Macedonia: 'MK',
	Madagascar: 'MG',
	Malawi: 'MW',
	Malaysia: 'MY',
	Maldives: 'MV',
	Mali: 'ML',
	Malta: 'MT',
	'Marshall Islands': 'MH',
	Martinique: 'MQ',
	Mauritania: 'MR',
	Mauritius: 'MU',
	Mayotte: 'YT',
	Mexico: 'MX',
	'Micronesia, Federated States of': 'FM',
	'Moldova, Republic of': 'MD',
	Monaco: 'MC',
	Mongolia: 'MN',
	Montenegro: 'ME',
	Montserrat: 'MS',
	Morocco: 'MA',
	Mozambique: 'MZ',
	Namibia: 'NA',
	Nauru: 'NR',
	Nepal: 'NP',
	Netherlands: 'NL',
	'New Caledonia': 'NC',
	'New Zealand': 'NZ',
	Nicaragua: 'NI',
	Niger: 'NE',
	Nigeria: 'NG',
	Niue: 'NU',
	'Norfolk Island': 'NF',
	'North Korea': 'KP',
	'Northern Mariana Islands': 'MP',
	Norway: 'NO',
	Oman: 'OM',
	Pakistan: 'PK',
	Palau: 'PW',
	Palestine: 'PS',
	Panama: 'PA',
	'Papua New Guinea': 'PG',
	Paraguay: 'PY',
	Peru: 'PE',
	Philippines: 'PH',
	'Pitcairn Islands': 'PN',
	Poland: 'PL',
	Portugal: 'PT',
	'Puerto Rico': 'PR',
	Qatar: 'QA',
	Reunion: 'RE',
	Romania: 'RO',
	Russia: 'RU',
	Rwanda: 'RW',
	'Saint Helena': 'SH',
	'Saint Kitts and Nevis': 'KN',
	'Saint Lucia': 'LC',
	'Saint Pierre and Miquelon': 'PM',
	'Saint Vincent and the Grenadines': 'VC',
	Samoa: 'WS',
	'San Marino': 'SM',
	'Sao Tome and Principe': 'ST',
	'Saudi Arabia': 'SA',
	Senegal: 'SN',
	Serbia: 'RS',
	Seychelles: 'SC',
	'Sierra Leone': 'SL',
	Singapore: 'SG',
	Slovakia: 'SK',
	Slovenia: 'SI',
	'Solomon Islands': 'SB',
	Somalia: 'SO',
	'South Africa': 'ZA',
	'South Georgia and the South Sandwich Islands': 'GS',
	'South Korea': 'KR',
	'Southern Sudan': 'SS',
	Spain: 'ES',
	'Sri Lanka': 'LK',
	Sudan: 'SD',
	Suriname: 'SR',
	Swaziland: 'SZ',
	Sweden: 'SE',
	Switzerland: 'CH',
	Syria: 'SY',
	Taiwan: 'TW',
	Tajikistan: 'TJ',
	Tanzania: 'TZ',
	Thailand: 'TH',
	Togo: 'TG',
	Tokelau: 'TK',
	Tonga: 'TO',
	'Trinidad & Tobago': 'TT',
	Tunisia: 'TN',
	Turkey: 'TR',
	Turkmenistan: 'TM',
	'Turks and Caicos Islands': 'TC',
	Tuvalu: 'TV',
	UK: 'GB',
	US: 'US',
	USA: 'US', // only in combinations
	Uganda: 'UG',
	Ukraine: 'UA',
	'United Arab Emirates': 'AE',
	Uruguay: 'UY',
	Uzbekistan: 'UZ',
	Vanuatu: 'VU',
	'Vatican City': 'VA',
	Venezuela: 'VE',
	Vietnam: 'VN',
	'Virgin Islands': 'VI', // U.S.
	'Wallis and Futuna': 'WF',
	'Western Sahara': 'EH',
	Yemen: 'YE',
	Zambia: 'ZM',
	Zimbabwe: 'ZW',
	// Special ISO codes
	Worldwide: 'XW',
	Europe: 'XE',
	// Historical ISO codes
	Czechoslovakia: 'XC',
	'German Democratic Republic (GDR)': 'XG',
	'Netherlands Antilles': 'AN',
	'Serbia and Montenegro': 'CS',
	USSR: 'SU',
	Yugoslavia: 'YU',
};

const _missingSubRegions = [
	{ label: 'Gaza Strip', value: '', pos: 114 }, // Palestine
	{ label: 'Wake Island', value: '', pos: 271 }, // United States Minor Outlying Islands
	{ label: 'West Bank', value: '', pos: 273 }, // Palestine
	{ label: 'Tibet', value: '', pos: 251 }, // China
	{ label: 'Abkhazia', value: 'GE-AB', pos: 31 }, // Georgia
	{ label: 'Zanzibar', value: '', pos: 278 }, // Tanzania
	{ label: 'Saar', value: '', pos: 219 }, // Germany
];

/** Separator that is used when Discogs joins multiple country/region names. */
const countrySeparator = /,? & |, /;

const _countryGroups = [
	{ label: 'Africa', value: '', pos: 22 },
	{ label: 'Asia', value: '', pos: 23 },
	{ label: 'Central America', value: '', pos: 24 },
	{ label: 'North America (inc Mexico)', value: '', pos: 26 },
	{ label: 'South America', value: '', pos: 27 },
	{ label: 'UK & Ireland', value: '', pos: 28 },
	{ label: 'USA & Canada', value: '', pos: 29 },
	{ label: 'Scandinavia', value: '', pos: 27 },
	{ label: 'Australia & New Zealand', value: '', pos: 23 },
	{ label: 'Benelux', value: '', pos: 23 },
	{ label: 'Gulf Cooperation Council', value: '', pos: 25 },
	{ label: 'UK, Europe & US', value: '', pos: 28 },
	{ label: 'UK & Europe', value: '', pos: 28 },
	{ label: 'Germany, Austria, & Switzerland', value: '', pos: 25 },
	{ label: 'Australasia', value: '', pos: 23 },
	{ label: 'USA, Canada & UK', value: '', pos: 29 },
	{ label: 'Germany & Switzerland', value: '', pos: 25 },
	{ label: 'UK & US', value: '', pos: 28 },
	{ label: 'France & Benelux', value: '', pos: 25 },
	{ label: 'UK & France', value: '', pos: 28 },
	{ label: 'UK, Europe & Japan', value: '', pos: 28 },
	{ label: 'Singapore, Malaysia & Hong Kong', value: '', pos: 232 },
	{ label: 'UK, Europe & Israel', value: '', pos: 28 },
	{ label: 'Middle East', value: '', pos: 25 },
	{ label: 'South East Asia', value: '', pos: 27 },
	{ label: 'USA, Canada & Europe', value: '', pos: 29 },
	{ label: 'Czech Republic & Slovakia', value: '', pos: 24 },
	{ label: 'USA & Europe', value: '', pos: 29 },
	{ label: 'South Pacific', value: '', pos: 239 },
	{ label: 'Singapore & Malaysia', value: '', pos: 232 },
	{ label: 'Hong Kong & Thailand', value: '', pos: 134 },
	{ label: 'North & South America', value: '', pos: 26 },
	{ label: 'UK & Germany', value: '', pos: 28 },
	{ label: 'Singapore, Malaysia, Hong Kong & Thailand', value: '', pos: 232 },
	{ label: 'Russia & CIS', value: '', pos: 217 },
];

const _historicalRegions = [
	{ label: 'Austria-Hungary', value: 'AUT/HUN', pos: 45 },
	{ label: 'Protectorate of Bohemia and Moravia', value: '', pos: 212 },
	{ label: 'Southern Rhodesia', value: '', pos: 236 }, // Zimbabwe
	{ label: 'Dahomey', value: '', pos: 90 }, // Benin
	{ label: 'Dutch East Indies', value: '', pos: 95 }, // Indonesia
	{ label: 'Ottoman Empire', value: '', pos: 200 },
	{ label: 'Rhodesia', value: '', pos: 216 }, // Zimbabwe
	{ label: 'Upper Volta', value: '', pos: 263 }, // Burkina Faso
	{ label: 'Zaire', value: '', pos: 278 }, // Democratic Republic of the Congo
	{ label: 'Bohemia', value: '', pos: 58 },
	{ label: 'Korea (pre-1945)', value: '', pos: 152 },
	{ label: 'Indochina', value: '', pos: 136 },
	{ label: 'South Vietnam', value: 'SVI', pos: 239 },
	{ label: 'South West Africa', value: '', pos: 239 }, // Namibia
	{ label: 'Belgian Congo', value: '', pos: 54 }, // Democratic Republic of the Congo
	{ label: 'Czech And Slovak Federative Republic', value: 'CSFR', pos: 24 },
	{ label: 'Italian East Africa', value: '', pos: 140 },
];
