// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from './routes/_app.tsx';
import * as $_middleware from './routes/_middleware.ts';
import * as $index from './routes/index.tsx';
import * as $release from './routes/release.tsx';
import * as $RegionList from './islands/RegionList.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
	routes: {
		'./routes/_app.tsx': $_app,
		'./routes/_middleware.ts': $_middleware,
		'./routes/index.tsx': $index,
		'./routes/release.tsx': $release,
	},
	islands: {
		'./islands/RegionList.tsx': $RegionList,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
